---
version: 0.2
phases:
  pre_build:
    commands:
      - REPOSITORY_URI=692609349536.dkr.ecr.ap-northeast-2.amazonaws.com/dynamodb-example
      - EKS_CLUSTER_NAME=dynamo-eks
      - export KUBECONFIG=$HOME/.kube/config
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - echo Deploy K8s...
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl apply -f k8s/deployment.yaml
      - kubectl rollout restart hello-deployment
