apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 8080